import { ExecutorContext, logger, workspaceRoot } from '@nx/devkit';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { dirname, join, isAbsolute } from 'path';
import { GenTypesExecutorSchema } from './schema';
import { resolveSupabasePath, loadEnvFile, isSupabaseRunning } from '../../utils/docker-utils';
import { runSupabaseCommand } from '../../utils/supabase-cli';

export async function genTypesExecutor(
  options: GenTypesExecutorSchema,
  context: ExecutorContext
): Promise<{ success: boolean }> {
  const workdir = resolveSupabasePath(options.supabaseDirectory, context);
  const env = loadEnvFile(workdir);

  // Resolve output path
  const projectRoot =
    context.projectsConfigurations?.projects[context.projectName || '']?.root || '';
  const outputPath = isAbsolute(options.outputPath)
    ? options.outputPath
    : join(workspaceRoot, projectRoot, options.outputPath);

  try {
    // Check if source is local and Supabase is running
    if (options.source !== 'linked' && options.source !== 'db-url') {
      const running = await isSupabaseRunning(workdir);
      if (!running) {
        logger.error('Supabase is not running. Start it first with:');
        logger.error(`  nx run ${context.projectName}:supabase-start`);
        return { success: false };
      }
    }

    logger.info('Generating TypeScript types...');

    // Build command
    const args: string[] = ['gen', 'types', 'typescript'];

    if (options.source === 'linked') {
      args.push('--linked');
    } else if (options.source === 'db-url' && options.dbUrl) {
      args.push(`--db-url="${options.dbUrl}"`);
    } else {
      args.push('--local');
    }

    // Add schemas
    const schemas = options.schemas || ['public'];
    schemas.forEach((schema) => {
      args.push(`--schema=${schema}`);
    });

    const { stdout, stderr } = await runSupabaseCommand(args.join(' '), {
      cwd: workdir,
      env,
    });

    if (stderr && !stdout) {
      logger.error(stderr);
      return { success: false };
    }

    // Ensure output directory exists
    const outputDir = dirname(outputPath);
    if (!existsSync(outputDir)) {
      mkdirSync(outputDir, { recursive: true });
    }

    // Write types file with header
    const typesContent = `// Generated by @nxsupabase/supabase
// DO NOT EDIT - Regenerate with: nx run ${context.projectName}:supabase-gen-types
// Source: ${options.source || 'local'}
// Generated at: ${new Date().toISOString()}

${stdout}`;

    writeFileSync(outputPath, typesContent);

    logger.info('');
    logger.info(`Types generated successfully at ${outputPath}`);

    return { success: true };
  } catch (error) {
    logger.error(`Failed to generate types: ${error instanceof Error ? error.message : error}`);
    return { success: false };
  }
}

export default genTypesExecutor;
